server:
  port: 8080

spring:
  application:
    name: Fortaleza API

  datasource:
    url: jdbc:postgresql://localhost:5432/fortaleza_db
    username: postgres
    password: camila1985
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# App Properties
fortaleza:
  app:
    jwtSecret: =======================BezKoder=Spring=======================
    jwtExpirationMs: 86400000
    cors:
      allowed-origins: "http://localhost:4200"