server:
  port: ${PORT:8080}   # Render usa la variable PORT

spring:
  application:
    name: Fortaleza API

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # en producción real mejor usar "validate"
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework: info
    org.hibernate.SQL: warn

# App Properties
fortaleza:
  app:
    jwtSecret: =======================BezKoder=Spring=======================
    jwtExpirationMs: 86400000
    cors:
      allowed-origins: "https://fortaleza-admin.vercel.app"